services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - livros-network

  mysql-service:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    container_name: mysql-service
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - livros-network
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=livros
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prodrigo@1988" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  livros:
    image: rodrigoamora/rodrigo-springboot:latest
    container_name: 'livros'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis
    ports:
      - "8080:8080"
    networks:
      - livros-network
    depends_on:
      - mysql-service
    restart: always

networks:
  livros-network:
    driver: bridge

volumes:
  redis-data:
  mysql-data:
    driver: local