spring.application.name=biblioteca-com-redis

### DATASOURCE ###
spring.datasource.url=jdbc:mysql://localhost:3306/livros?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rodrigo@1988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.dbcp2.default-auto-commit=true

### JPA / Hibernate ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

### REDIS ###
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

### Swagger UI ###
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

### SERVER ###
server.port=8080
